const constants = {
    GRAPHQL_URL : process.env.REACT_APP_GRAPHQL_URL,
    IS_AUTHENTICATED: 'MYAPP_IS_AUTHENTICATED',

    ERROR_CODE_DUPLICATE : 'ERROR_CODE_DUPLICATE',
    ERROR_CODE_UNAUTHENTICATED : 'UNAUTHENTICATED'
}

module.exports = constants